version: "3.8"

services:
  django:
    image: django
    container_name: django
    build: .
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - .:/hawsr
    networks:
      - webnet

  
  
networks:
  webnet:
  
    
