# Generated by Django 5.0.2 on 2024-02-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroffice',
            old_name='Office',
            new_name='office',
        ),
    ]
